/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}'
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9ff",
        "surface-tint": "#2659be",
        "outline-variant": "#c3c6d5",
        "background": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#b2c5ff",
        "error-container": "#ffdad6",
        "secondary-fixed": "#83fc8e",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb59b",
        "primary": "#00307c",
        "on-surface": "#0b1c30",
        "surface-dim": "#cbdbf5",
        "outline": "#737784",
        "on-tertiary-fixed": "#380d00",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "on-tertiary-container": "#ffa788",
        "on-secondary-fixed-variant": "#00531a",
        "secondary-fixed-dim": "#66df75",
        "on-error-container": "#93000a",
        "inverse-surface": "#213145",
        "surface-variant": "#d3e4fe",
        "on-primary-container": "#a3bbff",
        "surface-container-high": "#dce9ff",
        "secondary-container": "#80f98b",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-fixed": "#002106",
        "on-background": "#0b1c30",
        "primary-fixed": "#dae2ff",
        "on-tertiary-fixed-variant": "#812800",
        "surface-container": "#e5eeff",
        "tertiary-fixed": "#ffdbcf",
        "surface-container-highest": "#d3e4fe",
        "on-surface-variant": "#434653",
        "tertiary-container": "#8a2c01",
        "tertiary": "#641d00",
        "primary-fixed-dim": "#b2c5ff",
        "on-secondary-container": "#007327",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#001847",
        "secondary": "#006e25",
        "primary-container": "#0045ab",
        "surface-container-low": "#eff4ff",
        "on-primary-fixed-variant": "#0040a0",
        "on-error": "#ffffff"
      },
      spacing: {
        "lg": "24px",
        "xl": "32px",
        "md": "16px",
        "xs": "4px",
        "sidebar_width": "260px",
        "base": "4px",
        "gutter": "20px",
        "sm": "8px"
      },
      fontSize: {
        "title-sm": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-md": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}]
      },
      fontFamily: {
        "title-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "label-caps": ["Inter"],
        display: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        '2xs': '2px',
        xs: '4px',
        sm: '6px',
        md: '10px',
        lg: '14px',
        xl: '18px',
        '2xl': '24px',
        '3xl': '32px',
        '4xl': '40px',
        pill: '9999px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
