import { Company } from '../types';

export const mockCompanies: Company[] = [
  {
    id: 'comp-1',
    name: 'Công ty Cổ phần Viễn thông FPT',
    slug: 'fpt-telecom',
    logoUrl: 'https://cdn.haitrieu.com/wp-content/uploads/2022/01/Logo-FPT.png',
    coverUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
    address: 'Tòa nhà FPT, Số 10 Phạm Văn Bạch, Cầu Giấy, Hà Nội',
    shortDescription: 'Nhà cung cấp dịch vụ Internet và Viễn thông hàng đầu Việt Nam',
    description: 'FPT Telecom là một trong những nhà cung cấp dịch vụ Internet và Viễn thông hàng đầu tại Việt Nam.',
    website: 'https://fpt.vn',
    size: '1001_5000',
    industryId: 1,
    avgRating: 4.5,
    totalReviews: 120,
    totalJobs: 25,
    ownerId: 'user-1',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-2',
    name: 'Công ty Cổ phần VNG',
    slug: 'vng-corporation',
    logoUrl: 'https://vng.com.vn/assets/images/logo.png',
    coverUrl: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=1200&q=80',
    address: 'Z06 Đường số 13, Tân Thuận Đông, Quận 7, TP. Hồ Chí Minh',
    shortDescription: 'Kỳ lân công nghệ đầu tiên của Việt Nam',
    description: 'VNG là công ty công nghệ hàng đầu Việt Nam, nổi tiếng với các sản phẩm Zalo, Zing MP3, VNGGames.',
    website: 'https://vng.com.vn',
    size: '1001_5000',
    industryId: 2,
    avgRating: 4.8,
    totalReviews: 350,
    totalJobs: 18,
    ownerId: 'user-2',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-3',
    name: 'Tiki Corporation',
    slug: 'tiki-corporation',
    logoUrl: 'https://salt.tikicdn.com/ts/upload/ae/f4/6d/4664fae2b7ba50aba552eb5ad54f0081.png',
    coverUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1200&q=80',
    address: '52 Út Tịch, Phường 4, Tân Bình, TP. Hồ Chí Minh',
    shortDescription: 'Nền tảng thương mại điện tử hàng đầu Việt Nam',
    description: 'Tiki là sàn thương mại điện tử uy tín nhất Việt Nam với dịch vụ giao hàng nhanh TikiNow.',
    website: 'https://tiki.vn',
    size: '501_1000',
    industryId: 3,
    avgRating: 4.2,
    totalReviews: 85,
    totalJobs: 12,
    ownerId: 'user-3',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-4',
    name: 'Công ty Cổ phần Tập đoàn Masan',
    slug: 'masan-group',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/vi/thumb/9/9d/Masan_Group_logo.svg/1200px-Masan_Group_logo.svg.png',
    coverUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    address: 'Tòa nhà Central Plaza, 17 Lê Duẩn, Quận 1, TP. Hồ Chí Minh',
    shortDescription: 'Tập đoàn kinh tế tư nhân hàng đầu Việt Nam',
    description: 'Masan Group hoạt động trong các lĩnh vực hàng tiêu dùng, bán lẻ, vật liệu công nghệ cao.',
    website: 'https://masangroup.com',
    size: '1001_5000',
    industryId: 4,
    avgRating: 4.1,
    totalReviews: 210,
    totalJobs: 30,
    ownerId: 'user-4',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-5',
    name: 'Vinamilk',
    slug: 'vinamilk',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/vi/0/07/Logo_Vinamilk.svg',
    coverUrl: 'https://images.unsplash.com/photo-1568992687947-868a62a9f521?auto=format&fit=crop&w=1200&q=80',
    address: '10 Tân Trào, Tân Phú, Quận 7, TP. Hồ Chí Minh',
    shortDescription: 'Công ty Cổ phần Sữa Việt Nam',
    description: 'Vinamilk là doanh nghiệp hàng đầu trong ngành công nghiệp chế biến sữa Việt Nam.',
    website: 'https://vinamilk.com.vn',
    size: '1001_5000',
    industryId: 5,
    avgRating: 4.6,
    totalReviews: 400,
    totalJobs: 15,
    ownerId: 'user-5',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-6',
    name: 'Momo (M-Service)',
    slug: 'momo',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/vi/f/fe/MoMo_Logo.png',
    coverUrl: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=1200&q=80',
    address: 'Phú Mỹ Hưng Tower, 8 Hoàng Văn Thái, Quận 7, TP. Hồ Chí Minh',
    shortDescription: 'Ví điện tử số 1 Việt Nam',
    description: 'MoMo là siêu ứng dụng số 1 Việt Nam, cung cấp đa dạng các dịch vụ tài chính.',
    website: 'https://momo.vn',
    size: '501_1000',
    industryId: 6,
    avgRating: 4.4,
    totalReviews: 180,
    totalJobs: 40,
    ownerId: 'user-6',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
