import { Company } from '../types';

export const mockCompanies: Company[] = [
  {
    id: 'comp-1',
    name: 'Công ty Cổ phần Viễn thông FPT',
    slug: 'fpt-telecom',
    logoUrl: 'https://cdn.haitrieu.com/wp-content/uploads/2022/01/Logo-FPT.png',
    coverUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
    address: 'Tòa nhà FPT, Số 10 Phạm Văn Bạch, Cầu Giấy, Hà Nội',
    shortDescription: 'Nhà cung cấp dịch vụ Internet và Viễn thông hàng đầu Việt Nam',
    description: 'FPT Telecom là một trong những nhà cung cấp dịch vụ Internet và Viễn thông hàng đầu tại Việt Nam.',
    website: 'https://fpt.vn',
    size: '1001_5000',
    industryId: 1,
    avgRating: 4.5,
    totalReviews: 120,
    totalJobs: 25,
    ownerId: 'user-1',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-2',
    name: 'Công ty Cổ phần VNG',
    slug: 'vng-corporation',
    logoUrl: 'https://vng.com.vn/assets/images/logo.png',
    coverUrl: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=1200&q=80',
    address: 'Z06 Đường số 13, Tân Thuận Đông, Quận 7, TP. Hồ Chí Minh',
    shortDescription: 'Kỳ lân công nghệ đầu tiên của Việt Nam',
    description: 'VNG là công ty công nghệ hàng đầu Việt Nam, nổi tiếng với các sản phẩm Zalo, Zing MP3, VNGGames.',
    website: 'https://vng.com.vn',
    size: '1001_5000',
    industryId: 2,
    avgRating: 4.8,
    totalReviews: 350,
    totalJobs: 18,
    ownerId: 'user-2',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-3',
    name: 'Tiki Corporation',
    slug: 'tiki-corporation',
    logoUrl: 'https://salt.tikicdn.com/ts/upload/ae/f4/6d/4664fae2b7ba50aba552eb5ad54f0081.png',
    coverUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1200&q=80',
    address: '52 Út Tịch, Phường 4, Tân Bình, TP. Hồ Chí Minh',
    shortDescription: 'Nền tảng thương mại điện tử hàng đầu Việt Nam',
    description: 'Tiki là sàn thương mại điện tử uy tín nhất Việt Nam với dịch vụ giao hàng nhanh TikiNow.',
    website: 'https://tiki.vn',
    size: '501_1000',
    industryId: 3,
    avgRating: 4.2,
    totalReviews: 85,
    totalJobs: 12,
    ownerId: 'user-3',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-4',
    name: 'Công ty Cổ phần Tập đoàn Masan',
    slug: 'masan-group',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/vi/thumb/9/9d/Masan_Group_logo.svg/1200px-Masan_Group_logo.svg.png',
    coverUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    address: 'Tòa nhà Central Plaza, 17 Lê Duẩn, Quận 1, TP. Hồ Chí Minh',
    shortDescription: 'Tập đoàn kinh tế tư nhân hàng đầu Việt Nam',
    description: 'Masan Group hoạt động trong các lĩnh vực hàng tiêu dùng, bán lẻ, vật liệu công nghệ cao.',
    website: 'https://masangroup.com',
    size: '1001_5000',
    industryId: 4,
    avgRating: 4.1,
    totalReviews: 210,
    totalJobs: 30,
    ownerId: 'user-4',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-5',
    name: 'Vinamilk',
    slug: 'vinamilk',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/vi/0/07/Logo_Vinamilk.svg',
    coverUrl: 'https://images.unsplash.com/photo-1568992687947-868a62a9f521?auto=format&fit=crop&w=1200&q=80',
    address: '10 Tân Trào, Tân Phú, Quận 7, TP. Hồ Chí Minh',
    shortDescription: 'Công ty Cổ phần Sữa Việt Nam',
    description: 'Vinamilk là doanh nghiệp hàng đầu trong ngành công nghiệp chế biến sữa Việt Nam.',
    website: 'https://vinamilk.com.vn',
    size: '1001_5000',
    industryId: 5,
    avgRating: 4.6,
    totalReviews: 400,
    totalJobs: 15,
    ownerId: 'user-5',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-6',
    name: 'Momo (M-Service)',
    slug: 'momo',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/vi/f/fe/MoMo_Logo.png',
    coverUrl: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=1200&q=80',
    address: 'Phú Mỹ Hưng Tower, 8 Hoàng Văn Thái, Quận 7, TP. Hồ Chí Minh',
    shortDescription: 'Ví điện tử số 1 Việt Nam',
    description: 'MoMo là siêu ứng dụng số 1 Việt Nam, cung cấp đa dạng các dịch vụ tài chính.',
    website: 'https://momo.vn',
    size: '501_1000',
    industryId: 6,
    avgRating: 4.4,
    totalReviews: 180,
    totalJobs: 40,
    ownerId: 'user-6',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-7',
    name: 'Ngân hàng TMCP Quân Đội (MB Bank)',
    slug: 'mb-bank',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Logo_MB_new.png/1200px-Logo_MB_new.png',
    coverUrl: 'https://images.unsplash.com/photo-1501167733031-ce836a00a12e?auto=format&fit=crop&w=1200&q=80',
    address: '63 Lê Văn Lương, Cầu Giấy, Hà Nội',
    shortDescription: 'Ngân hàng TMCP Quân đội hàng đầu tại Việt Nam',
    description: 'MB Bank là một trong những ngân hàng thương mại lớn nhất Việt Nam.',
    website: 'https://mbbank.com.vn',
    size: '5000_plus',
    industryId: 6,
    avgRating: 4.5,
    totalReviews: 500,
    totalJobs: 120,
    ownerId: 'user-7',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-8',
    name: 'Công ty Cổ phần Tập đoàn Hòa Phát',
    slug: 'hoa-phat-group',
    logoUrl: 'https://www.hoaphat.com.vn/assets/images/logo.png',
    coverUrl: 'https://images.unsplash.com/photo-1518458028785-8fbcd101ebb9?auto=format&fit=crop&w=1200&q=80',
    address: 'KCN Phố Nối A, Giai Phạm, Yên Mỹ, Hưng Yên',
    shortDescription: 'Tập đoàn sản xuất công nghiệp hàng đầu Việt Nam',
    description: 'Hòa Phát là tập đoàn công nghiệp đa ngành, với lĩnh vực cốt lõi là sản xuất thép.',
    website: 'https://hoaphat.com.vn',
    size: '5000_plus',
    industryId: 7,
    avgRating: 4.3,
    totalReviews: 320,
    totalJobs: 55,
    ownerId: 'user-8',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-9',
    name: 'Công ty Cổ phần Thế Giới Di Động',
    slug: 'mwg',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Thegioididong.com_logo.svg/2560px-Thegioididong.com_logo.svg.png',
    coverUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=80',
    address: '128 Trần Quang Khải, Tân Định, Quận 1, TP. Hồ Chí Minh',
    shortDescription: 'Nhà bán lẻ số 1 Việt Nam',
    description: 'MWG là tập đoàn bán lẻ đa ngành hàng đầu tại Việt Nam, quản lý chuỗi Thegioididong, Dienmayxanh.',
    website: 'https://mwg.vn',
    size: '5000_plus',
    industryId: 4,
    avgRating: 4.0,
    totalReviews: 890,
    totalJobs: 210,
    ownerId: 'user-9',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-10',
    name: 'Công ty Cổ phần Đầu tư Địa ốc No Va (Novaland)',
    slug: 'novaland',
    logoUrl: 'https://www.novaland.com.vn/Data/Sites/1/media/novaland-logo.png',
    coverUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80',
    address: '65 Nguyễn Du, Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    shortDescription: 'Tập đoàn phát triển bất động sản uy tín',
    description: 'Novaland là nhà phát triển bất động sản hàng đầu với nhiều dự án lớn tại Việt Nam.',
    website: 'https://novaland.com.vn',
    size: '1001_5000',
    industryId: 6,
    avgRating: 4.2,
    totalReviews: 150,
    totalJobs: 35,
    ownerId: 'user-10',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-11',
    name: 'Tập đoàn Công nghiệp - Viễn thông Quân đội (Viettel)',
    slug: 'viettel',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Viettel_logo_2021.svg/1200px-Viettel_logo_2021.svg.png',
    coverUrl: 'https://images.unsplash.com/photo-1542382156909-9ae37b3f56fd?auto=format&fit=crop&w=1200&q=80',
    address: 'Lô D26, Khu đô thị mới Cầu Giấy, Yên Hòa, Cầu Giấy, Hà Nội',
    shortDescription: 'Tập đoàn Viễn thông và Công nghệ Thông tin lớn nhất Việt Nam',
    description: 'Viettel là tập đoàn viễn thông lớn nhất Việt Nam, đang mở rộng ra toàn cầu.',
    website: 'https://viettel.vn',
    size: '5000_plus',
    industryId: 2,
    avgRating: 4.6,
    totalReviews: 1200,
    totalJobs: 150,
    ownerId: 'user-11',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-12',
    name: 'Công ty Cổ phần Vàng bạc Đá quý Phú Nhuận (PNJ)',
    slug: 'pnj',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Logo_PNJ.svg/1200px-Logo_PNJ.svg.png',
    coverUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=80',
    address: '170E Phan Đăng Lưu, Phường 3, Phú Nhuận, TP. Hồ Chí Minh',
    shortDescription: 'Thương hiệu trang sức cao cấp hàng đầu Việt Nam',
    description: 'PNJ là công ty chế tác và bán lẻ trang sức lớn nhất Việt Nam.',
    website: 'https://pnj.com.vn',
    size: '1001_5000',
    industryId: 4,
    avgRating: 4.4,
    totalReviews: 280,
    totalJobs: 45,
    ownerId: 'user-12',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-13',
    name: 'Công ty Cổ phần Dược Hậu Giang (DHG Pharma)',
    slug: 'dhg-pharma',
    logoUrl: 'https://www.dhgpharma.com.vn/images/Logo-DHG.png',
    coverUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=1200&q=80',
    address: '288 Nguyễn Văn Cừ, An Hòa, Ninh Kiều, Cần Thơ',
    shortDescription: 'Doanh nghiệp dược phẩm hàng đầu Việt Nam',
    description: 'DHG Pharma là công ty sản xuất dược phẩm lớn nhất Việt Nam.',
    website: 'https://dhgpharma.com.vn',
    size: '1001_5000',
    industryId: 7,
    avgRating: 4.3,
    totalReviews: 190,
    totalJobs: 20,
    ownerId: 'user-13',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-14',
    name: 'Shopee Việt Nam',
    slug: 'shopee-vn',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Shopee.svg/1200px-Shopee.svg.png',
    coverUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=1200&q=80',
    address: 'Saigon Centre, 65 Lê Lợi, Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    shortDescription: 'Nền tảng thương mại điện tử hàng đầu Đông Nam Á',
    description: 'Shopee là nền tảng thương mại điện tử phổ biến nhất khu vực Đông Nam Á và Đài Loan.',
    website: 'https://shopee.vn',
    size: '1001_5000',
    industryId: 2,
    avgRating: 4.1,
    totalReviews: 650,
    totalJobs: 80,
    ownerId: 'user-14',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-15',
    name: 'KMS Technology',
    slug: 'kms-technology',
    logoUrl: 'https://kms-technology.com/wp-content/uploads/2018/10/kms-technology-logo.png',
    coverUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
    address: '2 Tản Viên, Phường 2, Tân Bình, TP. Hồ Chí Minh',
    shortDescription: 'Công ty cung cấp dịch vụ phát triển phần mềm toàn cầu',
    description: 'KMS Technology là công ty dịch vụ phần mềm quốc tế với các giải pháp công nghệ tiên tiến.',
    website: 'https://kms-technology.com',
    size: '1001_5000',
    industryId: 2,
    avgRating: 4.7,
    totalReviews: 310,
    totalJobs: 40,
    ownerId: 'user-15',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-16',
    name: 'Ngân hàng TMCP Kỹ Thương Việt Nam (Techcombank)',
    slug: 'techcombank',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Techcombank_logo.svg/1200px-Techcombank_logo.svg.png',
    coverUrl: 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?auto=format&fit=crop&w=1200&q=80',
    address: '6 Quang Trung, Trần Hưng Đạo, Hoàn Kiếm, Hà Nội',
    shortDescription: 'Ngân hàng tư nhân lớn nhất Việt Nam',
    description: 'Techcombank là một trong những ngân hàng thương mại cổ phần lớn nhất Việt Nam.',
    website: 'https://techcombank.com',
    size: '5000_plus',
    industryId: 6,
    avgRating: 4.5,
    totalReviews: 480,
    totalJobs: 95,
    ownerId: 'user-16',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-17',
    name: 'Công ty Cổ phần Hàng không Vietjet',
    slug: 'vietjet-air',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/VietJet_Air_logo.svg/1200px-VietJet_Air_logo.svg.png',
    coverUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80',
    address: '302 Kim Mã, Ngọc Khánh, Ba Đình, Hà Nội',
    shortDescription: 'Hãng hàng không thế hệ mới',
    description: 'Vietjet là hãng hàng không tư nhân đầu tiên của Việt Nam.',
    website: 'https://vietjetair.com',
    size: '1001_5000',
    industryId: 5,
    avgRating: 4.0,
    totalReviews: 220,
    totalJobs: 60,
    ownerId: 'user-17',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-18',
    name: 'Công ty Cổ phần Tập đoàn Xây dựng Hòa Bình',
    slug: 'hoa-binh-corp',
    logoUrl: 'https://hbcg.vn/assets/images/logo.png',
    coverUrl: 'https://images.unsplash.com/photo-1541888087405-eb81f579d46f?auto=format&fit=crop&w=1200&q=80',
    address: 'Tòa nhà Pax Sky, 123 Nguyễn Đình Chiểu, Phường 6, Quận 3, TP. Hồ Chí Minh',
    shortDescription: 'Nhà thầu xây dựng hàng đầu Việt Nam',
    description: 'Hòa Bình là một trong những nhà thầu xây dựng uy tín nhất Việt Nam.',
    website: 'https://hbcg.vn',
    size: '1001_5000',
    industryId: 7,
    avgRating: 4.2,
    totalReviews: 170,
    totalJobs: 28,
    ownerId: 'user-18',
    isVerified: true,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const mockIndustries = [
  { id: '1', name: 'IT - Phần mềm', count: '540+' },
  { id: '2', name: 'Công nghệ', count: '440+' },
  { id: '3', name: 'Thương mại điện tử', count: '100+' },
  { id: '4', name: 'Sản xuất', count: '35+' },
  { id: '5', name: 'Ngân hàng', count: '315+' },
  { id: '6', name: 'Bảo hiểm', count: '200+' },
  { id: '7', name: 'Xây dựng', count: '150+' },
];
