import { Job } from '../types';

export const mockJobs: Job[] = [
  {
    id: '550e8400-e29b-41d4-a716-446655440001',
    companyId: 'comp-1',
    title: 'Senior Frontend Developer (React/Vue)',
    slug: 'senior-frontend-developer-react-vue',
    description: 'We are looking for a Senior Frontend Developer to join our core team...',
    requirements: '- At least 3 years of experience with React/Vue\n- Strong understanding of JavaScript/TypeScript\n- Experience with state management (Redux, Vuex, etc.)',
    benefits: '- Competitive salary\n- 13th month salary\n- Premium healthcare insurance',
    address: 'Tòa nhà FPT, Số 10 Phạm Văn Bạch, Cầu Giấy',
    provinceId: 1, // Hà Nội
    jobType: 'full_time',
    experienceLevel: 'senior',
    salaryMin: 1500,
    salaryMax: 2500,
    status: 'published',
    quantity: 1,
    isSalaryPublic: true,
    isRemote: false,
    viewCount: 100,
    applyCount: 10,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    postedBy: 'user-1',
    categoryId: 1,
    salaryType: 'monthly',
    salaryCurrency: 'USD',
    saveCount: 45,
    company: {
      id: 'comp-1',
      name: 'Công ty Cổ phần Viễn thông FPT',
      logoUrl: 'https://cdn.haitrieu.com/wp-content/uploads/2022/01/Logo-FPT.png',
      slug: 'fpt-telecom',
      ownerId: 'user-1',
      totalJobs: 25,
      totalReviews: 120,
      isVerified: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    jobSkills: [
      { id: 1, jobId: '550e8400-e29b-41d4-a716-446655440001', skillId: 1, isRequired: true, skill: { id: 1, name: 'ReactJS' } },
      { id: 2, jobId: '550e8400-e29b-41d4-a716-446655440001', skillId: 2, isRequired: true, skill: { id: 2, name: 'TypeScript' } },
      { id: 3, jobId: '550e8400-e29b-41d4-a716-446655440001', skillId: 3, isRequired: false, skill: { id: 3, name: 'VueJS' } }
    ]
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440002',
    companyId: 'comp-2',
    title: 'Middle Backend Engineer (NodeJS/Go)',
    slug: 'middle-backend-engineer-nodejs-go',
    description: 'VNG đang tìm kiếm Middle Backend Engineer tham gia phát triển hệ thống ZaloPay...',
    requirements: '- 2+ years of experience with NodeJS or Golang\n- Experience with Microservices architecture\n- Good knowledge of SQL and NoSQL databases',
    benefits: '- 14+ months of salary\n- Macbook Pro provided\n- Free lunch and snacks',
    address: 'Z06 Đường số 13, Tân Thuận Đông, Quận 7',
    provinceId: 2, // HCM
    jobType: 'full_time',
    experienceLevel: 'mid',
    salaryMin: 1200,
    salaryMax: 2000,
    status: 'published',
    quantity: 2,
    isSalaryPublic: true,
    isRemote: false,
    viewCount: 200,
    applyCount: 20,
    expiresAt: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    postedBy: 'user-2',
    categoryId: 2,
    salaryType: 'monthly',
    salaryCurrency: 'USD',
    saveCount: 120,
    company: {
      id: 'comp-2',
      name: 'Công ty Cổ phần VNG',
      logoUrl: 'https://vng.com.vn/assets/images/logo.png',
      slug: 'vng-corporation',
      ownerId: 'user-2',
      totalJobs: 18,
      totalReviews: 350,
      isVerified: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    jobSkills: [
      { id: 4, jobId: '550e8400-e29b-41d4-a716-446655440002', skillId: 4, isRequired: true, skill: { id: 4, name: 'NodeJS' } },
      { id: 5, jobId: '550e8400-e29b-41d4-a716-446655440002', skillId: 5, isRequired: true, skill: { id: 5, name: 'Golang' } },
      { id: 6, jobId: '550e8400-e29b-41d4-a716-446655440002', skillId: 6, isRequired: false, skill: { id: 6, name: 'Microservices' } }
    ]
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440003',
    companyId: 'comp-3',
    title: 'Senior DevOps Engineer',
    slug: 'senior-devops-engineer',
    description: 'Join our infrastructure team to build and maintain highly available systems...',
    requirements: '- Deep knowledge of AWS/GCP\n- Experience with Kubernetes and Docker\n- CI/CD pipeline automation (Jenkins, GitLab CI)',
    benefits: '- Stock options\n- Flexible working hours\n- Remote work up to 2 days/week',
    address: '52 Út Tịch, Phường 4, Tân Bình',
    provinceId: 2, // HCM
    jobType: 'full_time',
    experienceLevel: 'senior',
    salaryMin: 2000,
    salaryMax: 3500,
    status: 'published',
    quantity: 1,
    isSalaryPublic: true,
    isRemote: true,
    viewCount: 300,
    applyCount: 30,
    expiresAt: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    postedBy: 'user-3',
    categoryId: 3,
    salaryType: 'monthly',
    salaryCurrency: 'USD',
    saveCount: 85,
    company: {
      id: 'comp-3',
      name: 'Tiki Corporation',
      logoUrl: 'https://salt.tikicdn.com/ts/upload/ae/f4/6d/4664fae2b7ba50aba552eb5ad54f0081.png',
      slug: 'tiki-corporation',
      ownerId: 'user-3',
      totalJobs: 12,
      totalReviews: 85,
      isVerified: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    jobSkills: [
      { id: 7, jobId: '550e8400-e29b-41d4-a716-446655440003', skillId: 7, isRequired: true, skill: { id: 7, name: 'AWS' } },
      { id: 8, jobId: '550e8400-e29b-41d4-a716-446655440003', skillId: 8, isRequired: true, skill: { id: 8, name: 'Kubernetes' } },
      { id: 9, jobId: '550e8400-e29b-41d4-a716-446655440003', skillId: 9, isRequired: true, skill: { id: 9, name: 'Docker' } }
    ]
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440004',
    companyId: 'comp-4',
    title: 'Fresher / Junior Data Analyst',
    slug: 'fresher-junior-data-analyst',
    description: 'We are looking for passionate Data Analysts to join our Data team...',
    requirements: '- Degree in Computer Science, Statistics, or Mathematics\n- Basic knowledge of SQL and Python/R\n- Good analytical and problem-solving skills',
    benefits: '- Comprehensive training program\n- Mentor 1-1\n- Competitive fresher package',
    address: 'Tòa nhà Central Plaza, 17 Lê Duẩn, Quận 1',
    provinceId: 2, // HCM
    jobType: 'full_time',
    experienceLevel: 'fresher',
    salaryMin: 400,
    salaryMax: 800,
    status: 'published',
    quantity: 5,
    isSalaryPublic: true,
    isRemote: false,
    viewCount: 400,
    applyCount: 40,
    expiresAt: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    postedBy: 'user-4',
    categoryId: 4,
    salaryType: 'monthly',
    salaryCurrency: 'USD',
    saveCount: 300,
    company: {
      id: 'comp-4',
      name: 'Công ty Cổ phần Tập đoàn Masan',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/vi/thumb/9/9d/Masan_Group_logo.svg/1200px-Masan_Group_logo.svg.png',
      slug: 'masan-group',
      ownerId: 'user-4',
      totalJobs: 30,
      totalReviews: 210,
      isVerified: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    jobSkills: [
      { id: 10, jobId: '550e8400-e29b-41d4-a716-446655440004', skillId: 10, isRequired: true, skill: { id: 10, name: 'SQL' } },
      { id: 11, jobId: '550e8400-e29b-41d4-a716-446655440004', skillId: 11, isRequired: true, skill: { id: 11, name: 'Python' } },
      { id: 12, jobId: '550e8400-e29b-41d4-a716-446655440004', skillId: 12, isRequired: false, skill: { id: 12, name: 'Data Analysis' } }
    ]
  }
];
