import { Job } from '../types';

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    companyId: 'comp-1',
    title: 'Senior Frontend Developer (React/Vue)',
    slug: 'senior-frontend-developer-react-vue',
    description: '<p>Chúng tôi đang tìm kiếm một <strong>Senior Frontend Developer</strong> gia nhập đội ngũ nòng cốt để phát triển các sản phẩm chiến lược của công ty.</p><ul><li>Tham gia thiết kế và xây dựng kiến trúc cho các ứng dụng web quy mô lớn.</li><li>Làm việc chặt chẽ với team UI/UX để đảm bảo trải nghiệm người dùng tốt nhất.</li><li>Tối ưu hóa hiệu năng (performance optimization) và đảm bảo tính bảo mật cho Frontend.</li><li>Mentor cho các bạn Junior/Middle trong team.</li></ul>',
    requirements: '<p><strong>Yêu cầu bắt buộc:</strong></p><ul><li>Có ít nhất <strong>3 năm kinh nghiệm</strong> làm việc thực tế với ReactJS hoặc VueJS.</li><li>Nắm vững kiến thức về JavaScript (ES6+), TypeScript, HTML5, CSS3/SASS.</li><li>Có kinh nghiệm với các state management pattern (Redux, Vuex, Zustand...).</li><li>Hiểu biết về RESTful API và GraphQL.</li></ul><p><strong>Điểm cộng:</strong></p><ul><li>Từng làm việc với Next.js hoặc Nuxt.js.</li><li>Có tư duy tốt về UI/UX và animation.</li></ul>',
    benefits: '<ul><li>Mức lương cạnh tranh: <strong>$1500 - $2500</strong> tùy theo năng lực.</li><li>Lương tháng 13 + Thưởng hiệu quả công việc (1-3 tháng lương).</li><li>Bảo hiểm sức khỏe cao cấp (PVI/Bảo Việt) cho bản thân và gia đình.</li><li>Cung cấp Macbook Pro M2/M3 và màn hình rời để làm việc.</li><li>Review lương 2 lần/năm.</li><li>Tham gia các khóa học nâng cao kỹ năng do công ty tài trợ.</li></ul>',
    address: 'Tòa nhà FPT, Số 10 Phạm Văn Bạch, Cầu Giấy',
    provinceId: 1, // Hà Nội
    jobType: 'full_time',
    experienceLevel: 'senior',
    salaryMin: 15000000,
    salaryMax: 35000000,
    status: 'published',
    quantity: 2,
    isSalaryPublic: true,
    isRemote: false,
    viewCount: 1250,
    applyCount: 45,
    expiresAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // Sắp hết hạn (2 ngày)
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    postedBy: 'user-1',
    categoryId: 1,
    salaryType: 'monthly',
    salaryCurrency: 'VND',
    saveCount: 145,
    company: {
      id: 'comp-1',
      name: 'Công ty Cổ phần Viễn thông FPT',
      logoUrl: 'https://cdn.haitrieu.com/wp-content/uploads/2022/01/Logo-FPT.png',
      slug: 'fpt-telecom',
      ownerId: 'user-1',
      totalJobs: 25,
      totalReviews: 120,
      avgRating: 4.5,
      size: '5000_plus',
      isVerified: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    jobSkills: [
      { id: 1, jobId: 'job-1', skillId: 1, isRequired: true, skill: { id: 1, name: 'ReactJS' } },
      { id: 2, jobId: 'job-1', skillId: 2, isRequired: true, skill: { id: 2, name: 'TypeScript' } },
      { id: 3, jobId: 'job-1', skillId: 3, isRequired: false, skill: { id: 3, name: 'VueJS' } }
    ]
  },
  {
    id: 'job-2',
    companyId: 'comp-2',
    title: 'Middle Backend Engineer (NodeJS/Go)',
    slug: 'middle-backend-engineer-nodejs-go',
    description: '<p>VNG đang tìm kiếm <strong>Middle Backend Engineer</strong> tham gia phát triển hệ thống lõi cho ZaloPay, phục vụ hàng chục triệu người dùng.</p><ul><li>Phát triển các API microservices hiệu năng cao bằng NodeJS hoặc Golang.</li><li>Tối ưu hóa query database (MySQL, PostgreSQL) và caching (Redis).</li><li>Xử lý các bài toán về concurrency, high availability và fault tolerance.</li></ul>',
    requirements: '<p><strong>Yêu cầu chuyên môn:</strong></p><ul><li><strong>2+ năm kinh nghiệm</strong> làm việc với NodeJS hoặc Golang.</li><li>Hiểu rõ kiến trúc Microservices và RESTful API.</li><li>Kinh nghiệm làm việc với Message Brokers (Kafka, RabbitMQ).</li><li>Sử dụng thành thạo Git, Docker.</li></ul>',
    benefits: '<ul><li>Gói thu nhập lên đến <strong>15 tháng lương/năm</strong>.</li><li>Laptop cấp mới 100% (Macbook Pro).</li><li>Hỗ trợ ăn trưa, gửi xe miễn phí, phòng tập gym hiện đại tại campus.</li><li>Môi trường làm việc năng động, nhiều câu lạc bộ (Bóng đá, Cầu lông, Esport...).</li></ul>',
    address: 'VNG Campus, Khu chế xuất Tân Thuận, Quận 7',
    provinceId: 2, // HCM
    jobType: 'full_time',
    experienceLevel: 'mid',
    salaryMin: 20000000,
    salaryMax: 40000000,
    status: 'published',
    quantity: 5,
    isSalaryPublic: true,
    isRemote: false,
    viewCount: 3200,
    applyCount: 120,
    expiresAt: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    postedBy: 'user-2',
    categoryId: 2,
    salaryType: 'monthly',
    salaryCurrency: 'VND',
    saveCount: 320,
    company: {
      id: 'comp-2',
      name: 'Công ty Cổ phần VNG',
      logoUrl: 'https://vng.com.vn/assets/images/logo.png',
      slug: 'vng-corporation',
      ownerId: 'user-2',
      totalJobs: 45,
      totalReviews: 850,
      avgRating: 4.8,
      size: '5000_plus',
      isVerified: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    jobSkills: [
      { id: 4, jobId: 'job-2', skillId: 4, isRequired: true, skill: { id: 4, name: 'NodeJS' } },
      { id: 5, jobId: 'job-2', skillId: 5, isRequired: true, skill: { id: 5, name: 'Golang' } },
      { id: 6, jobId: 'job-2', skillId: 6, isRequired: false, skill: { id: 6, name: 'Microservices' } },
      { id: 13, jobId: 'job-2', skillId: 13, isRequired: true, skill: { id: 13, name: 'Redis' } }
    ]
  },
  {
    id: 'job-3',
    companyId: 'comp-3',
    title: 'Senior DevOps Engineer',
    slug: 'senior-devops-engineer',
    description: '<p>Tiki đang mở rộng hệ thống hạ tầng và cần tuyển dụng chuyên gia DevOps để đảm bảo độ ổn định và scale cho nền tảng thương mại điện tử.</p><ul><li>Thiết kế, triển khai và vận hành hệ thống hạ tầng trên nền tảng AWS.</li><li>Xây dựng và tối ưu hóa hệ thống CI/CD pipelines.</li><li>Triển khai giám sát (monitoring), cảnh báo (alerting) và phân tích log.</li><li>Hỗ trợ team Dev trong quá trình deployment và troubleshooting.</li></ul>',
    requirements: '<p><strong>Yêu cầu:</strong></p><ul><li>Có ít nhất <strong>4 năm kinh nghiệm</strong> ở vị trí DevOps / System Admin.</li><li>Thành thạo hệ sinh thái AWS (EC2, S3, RDS, EKS, VPC...).</li><li>Kinh nghiệm sâu rộng về Kubernetes, Docker, Helm.</li><li>Thành thạo các công cụ CI/CD (GitLab CI, Jenkins, ArgoCD).</li><li>Có kiến thức về IaC (Terraform, Ansible).</li></ul>',
    benefits: '<ul><li>Mức lương thỏa thuận không giới hạn tùy năng lực.</li><li>Quyền chọn mua cổ phần (Stock options).</li><li>Làm việc từ xa (Remote) linh hoạt.</li><li>Cấp thẻ bảo hiểm sức khỏe cho nhân viên và người thân.</li></ul>',
    address: '52 Út Tịch, Phường 4, Tân Bình',
    provinceId: 2, // HCM
    jobType: 'full_time',
    experienceLevel: 'senior',
    status: 'published',
    quantity: 1,
    isSalaryPublic: false,
    isRemote: true,
    viewCount: 850,
    applyCount: 15,
    expiresAt: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    postedBy: 'user-3',
    categoryId: 3,
    salaryType: 'monthly',
    salaryCurrency: 'USD',
    saveCount: 95,
    company: {
      id: 'comp-3',
      name: 'Tiki Corporation',
      logoUrl: 'https://salt.tikicdn.com/ts/upload/ae/f4/6d/4664fae2b7ba50aba552eb5ad54f0081.png',
      slug: 'tiki-corporation',
      ownerId: 'user-3',
      totalJobs: 12,
      totalReviews: 145,
      avgRating: 4.2,
      size: '501_1000',
      isVerified: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    jobSkills: [
      { id: 7, jobId: 'job-3', skillId: 7, isRequired: true, skill: { id: 7, name: 'AWS' } },
      { id: 8, jobId: 'job-3', skillId: 8, isRequired: true, skill: { id: 8, name: 'Kubernetes' } },
      { id: 9, jobId: 'job-3', skillId: 9, isRequired: true, skill: { id: 9, name: 'Terraform' } }
    ]
  },
  {
    id: 'job-4',
    companyId: 'comp-4',
    title: 'Fresher / Junior Data Analyst',
    slug: 'fresher-junior-data-analyst',
    description: '<p>Tập đoàn Masan đang tìm kiếm các bạn trẻ đam mê phân tích dữ liệu tham gia vào quá trình chuyển đổi số của hệ thống bán lẻ lớn nhất Việt Nam.</p><ul><li>Phân tích dữ liệu bán hàng, hành vi khách hàng để đưa ra insights.</li><li>Xây dựng các dashboard báo cáo trực quan (PowerBI/Tableau).</li><li>Hỗ trợ các phòng ban khác trong việc truy xuất và xử lý dữ liệu.</li></ul>',
    requirements: '<p><strong>Yêu cầu:</strong></p><ul><li>Tốt nghiệp Đại học chuyên ngành Toán, Thống kê, Khoa học dữ liệu, Hệ thống thông tin...</li><li>Sử dụng thành thạo SQL để truy vấn dữ liệu.</li><li>Có kiến thức cơ bản về Python hoặc R là một lợi thế.</li><li>Tư duy logic, nhạy bén với số liệu.</li></ul>',
    benefits: '<ul><li>Tham gia chương trình đào tạo bài bản cho Fresher.</li><li>Có Mentor hướng dẫn 1-1 trong 6 tháng đầu.</li><li>Thu nhập khởi điểm hấp dẫn (Từ 10 - 15 triệu/tháng).</li><li>Cơ hội thăng tiến rõ ràng lên Data Scientist hoặc Data Engineer.</li></ul>',
    address: 'Tòa nhà Central Plaza, 17 Lê Duẩn, Quận 1',
    provinceId: 2, // HCM
    jobType: 'full_time',
    experienceLevel: 'fresher',
    salaryMin: 10000000,
    salaryMax: 15000000,
    status: 'published',
    quantity: 5,
    isSalaryPublic: true,
    isRemote: false,
    viewCount: 4500,
    applyCount: 250,
    expiresAt: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    postedBy: 'user-4',
    categoryId: 4,
    salaryType: 'monthly',
    salaryCurrency: 'VND',
    saveCount: 500,
    company: {
      id: 'comp-4',
      name: 'Công ty Cổ phần Tập đoàn Masan',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/vi/thumb/9/9d/Masan_Group_logo.svg/1200px-Masan_Group_logo.svg.png',
      slug: 'masan-group',
      ownerId: 'user-4',
      totalJobs: 50,
      totalReviews: 320,
      avgRating: 4.0,
      size: '5000_plus',
      isVerified: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    jobSkills: [
      { id: 10, jobId: 'job-4', skillId: 10, isRequired: true, skill: { id: 10, name: 'SQL' } },
      { id: 11, jobId: 'job-4', skillId: 11, isRequired: false, skill: { id: 11, name: 'Python' } },
      { id: 12, jobId: 'job-4', skillId: 12, isRequired: true, skill: { id: 12, name: 'Data Analysis' } }
    ]
  },
  {
    id: 'job-5',
    companyId: 'comp-5',
    title: 'Chuyên Viên Chăm Sóc Khách Hàng (Không Yêu Cầu Kinh Nghiệm)',
    slug: 'chuyen-vien-cham-soc-khach-hang-khong-yeu-cau-kinh-nghiem',
    description: '<p>Cơ hội tuyệt vời cho các bạn trẻ năng động! Chúng tôi đang tìm kiếm <strong>Chuyên viên Chăm sóc khách hàng</strong>.</p><ul><li>Tiếp nhận cuộc gọi, giải đáp thắc mắc của khách hàng về dịch vụ của công ty.</li><li>Ghi nhận khiếu nại và chuyển đến các bộ phận liên quan để xử lý.</li><li>Đảm bảo tỷ lệ hài lòng của khách hàng (CSAT) đạt mức yêu cầu.</li><li>Cập nhật thông tin khách hàng vào hệ thống CRM.</li></ul>',
    requirements: '<p><strong>Yêu cầu ứng viên:</strong></p><ul><li>Tốt nghiệp THPT trở lên, ưu tiên các bạn sinh viên mới ra trường.</li><li>Giọng nói chuẩn, không nói ngọng, không nói tiếng địa phương.</li><li>Kỹ năng giao tiếp và xử lý tình huống tốt.</li><li>Chăm chỉ, chịu khó và có tinh thần trách nhiệm cao.</li><li>Biết sử dụng tin học văn phòng cơ bản (Word, Excel).</li></ul>',
    benefits: '<ul><li>Lương cứng: <strong>8.000.000 - 10.000.000 VNĐ/tháng</strong> + Thưởng KPIs.</li><li>Thử việc hưởng 100% lương cứng.</li><li>Được đào tạo bài bản về kỹ năng giao tiếp và kiến thức sản phẩm.</li><li>Môi trường làm việc trẻ trung, năng động, sếp tâm lý.</li><li>Đầy đủ chế độ BHXH, BHYT, BHTN theo quy định.</li></ul>',
    address: 'Tòa nhà Viettel, 285 Cách Mạng Tháng Tám, Quận 10',
    provinceId: 2, // HCM
    jobType: 'full_time',
    experienceLevel: 'fresher',
    salaryMin: 8000000,
    salaryMax: 15000000,
    status: 'published',
    quantity: 10,
    isSalaryPublic: true,
    isRemote: false,
    viewCount: 5200,
    applyCount: 310,
    expiresAt: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    postedBy: 'user-5',
    categoryId: 5,
    salaryType: 'monthly',
    salaryCurrency: 'VND',
    saveCount: 420,
    company: {
      id: 'comp-5',
      name: 'Công ty Cổ phần BPO Mắt Bão',
      logoUrl: 'https://cdn.haitrieu.com/wp-content/uploads/2022/10/Logo-Mat-Bao.png',
      slug: 'mat-bao-bpo',
      ownerId: 'user-5',
      totalJobs: 15,
      totalReviews: 210,
      avgRating: 4.3,
      size: '5000_plus',
      isVerified: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    jobSkills: []
  },
  {
    id: 'job-6',
    companyId: 'comp-6',
    title: 'UI/UX Designer (Mid/Senior) - Product Team',
    slug: 'ui-ux-designer-mid-senior-product-team',
    description: '<p>Tham gia vào đội ngũ Product của Shopee, thiết kế trải nghiệm người dùng cho hàng triệu khách hàng Đông Nam Á.</p><ul><li>Thiết kế wireframe, mockup, và prototype cho ứng dụng web và mobile.</li><li>Phối hợp cùng Product Manager và Engineer để hiện thực hóa ý tưởng.</li><li>Tiến hành user research, A/B testing để tối ưu hóa trải nghiệm (UX).</li><li>Duy trì và phát triển Design System của công ty.</li></ul>',
    requirements: '<p><strong>Yêu cầu:</strong></p><ul><li>Ít nhất <strong>2 năm kinh nghiệm</strong> làm UI/UX Designer cho các sản phẩm công nghệ.</li><li>Sử dụng thành thạo Figma, Sketch, hoặc Adobe XD.</li><li>Có tư duy tốt về User-Centered Design (UCD).</li><li>Portfolio thể hiện rõ quy trình thiết kế và khả năng giải quyết vấn đề.</li></ul>',
    benefits: '<ul><li>Lương: <strong>$1000 - $2000</strong> (Đánh giá theo năng lực).</li><li>Phụ cấp ăn trưa, đi lại, điện thoại.</li><li>Môi trường quốc tế, giao tiếp tiếng Anh 100%.</li><li>15 ngày phép/năm, review lương mỗi 6 tháng.</li></ul>',
    address: 'Saigon Centre Tower 2, 67 Lê Lợi, Quận 1',
    provinceId: 2, // HCM
    jobType: 'full_time',
    experienceLevel: 'mid',
    salaryMin: 25000000,
    salaryMax: 50000000,
    status: 'published',
    quantity: 2,
    isSalaryPublic: true,
    isRemote: false,
    viewCount: 2800,
    applyCount: 85,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    postedBy: 'user-6',
    categoryId: 6,
    salaryType: 'monthly',
    salaryCurrency: 'VND',
    saveCount: 210,
    company: {
      id: 'comp-6',
      name: 'Shopee Việt Nam',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Shopee.svg/1200px-Shopee.svg.png',
      slug: 'shopee-vietnam',
      ownerId: 'user-6',
      totalJobs: 120,
      totalReviews: 1500,
      avgRating: 4.6,
      size: '5000_plus',
      isVerified: true,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    jobSkills: [
      { id: 14, jobId: 'job-6', skillId: 14, isRequired: true, skill: { id: 14, name: 'Figma' } },
      { id: 15, jobId: 'job-6', skillId: 15, isRequired: true, skill: { id: 15, name: 'UI/UX' } }
    ]
  }
];
